openapi: 3.0.0
info:
  title: Pet Shelter API
  version: 0.0.0-alpha0
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    enum: [OK]
  /pets:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pet:
                  $ref: '#/components/schemas/Pet'
      responses:
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
        409:
          description: Name and Breed are not unique
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: '#/components/schemas/Pet'
  /pets/{petid}:
    parameters:
      - name: petid
        in: path
        schema:
          type: string
        required: true
    get:
      responses:
        404:
          description: Not Found
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  pet:
                    $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: number
          readOnly: true
        name:
          type: string
        type:
          type: string
        breed:
          type: string
        location:
          type: object
          properties:
            type:
              enum: ['Point']
            coordinates:
              type: array
              items:
                type: number